# TAT-C: Collect Observations Core Functions Example

Dr. Paul Grogan, I. Josue Tapia-Tamayo, Isaac Feldman
Collective Design (CoDe) Lab
Stevens Institute of Technology, School of Systems and Enterprises


This example demonstrates how to use direct function calls of the low-level TAT-C library to model observations of single point  by a single satellite using an orbit derived from an existing Two Line Element (TLE) set.

## Dependencies

### Standard Python Libraries
This example is compatible with python 3.8.10 and makes use of the standard `pandas` and `datetime` libraries.

In [1]:
import pandas as pd
from datetime import datetime, timezone, timedelta

### TAT-C Library
Additionally, this example makes use of the low-level `tatc` library. If you do not have this installed, navigate to the main `tatc-v3` file and make sure you have followed all the instructions for installation of TAT-C.

In [1]:
from tatc.analysis.coverage import collect_multi_observations
from tatc.schemas.satellite import Satellite
from tatc.schemas.instrument import Instrument
from tatc.schemas.orbit import TwoLineElements
from tatc.schemas.point import Point

## Establish the Mission Architecture and Key Information
The first step in modeling a mission with TAT-C is to establish the key mission parameters -- specifically the satellites, the mission time frame and points on the ground for observation.

### Modeling Satellite Architecture
First we define the satellites for a mission. In this example we define one satellite (NOAA-1) with a single instrument and an orbit derived from a known two-line element set (TLE). This uses the `TwoLineElements` class from `tatc.schemas.orbit` and the `Instrument` class from `tatc.schemas.instrument`.

In [3]:
# Save the NOAA-1 TLE as a list where the first element of the list is the first line
# of the TLE and the second list element is the second line
tle = ['1 04793U 70106A   22044.41526573 -.00000035  00000+0  54783-4 0  9991',
        '2 04793 101.5750 111.2777 0031771 203.0437 167.8944 12.54003052342042']

# Derive the satellite orbit from the TLE
orbit = TwoLineElements(type='tle',
                        tle=tle)

# Initialize the instrument for the satellite to make observations
instrument = Instrument(name='Lead Instrument', field_of_regard=180)

# Define the satellite from the orbit and instrument
sat = Satellite(name='NOAA1',
                type='satellite',
                orbit=orbit,
                instruments=[instrument])

### Modeling Mission Parameters
Next we define the mission parameters, specifically the target point -- using the `Point` class from `tatc.schemas.point` -- and the start and end time of the mission window -- using the `datetime` and `timedelta` objects from the python `datetime` module.

In [4]:
# Define a target points for observations
point = Point(id=0, latitude=40.74259, longitude=-74.02686)

# Set the start date to be January, 1, 2021 at noon (12 pm) UTC
start = datetime(year=2021, month=1, day=1, hour=12, minute=0, second=0, tzinfo=timezone.utc)

# Set the end date to be 30 days after the start date
end = start + timedelta(days=30)

## Collecting Observations
Finally we utilize the `collect_observations` function from `tatc.analysis.coverage` to determine all the opportunities for the satellite to observe the point with the specified instrument.

In [5]:
results = collect_observations(point, sat, instrument, start, end, omit_solar=False)
results

,point_id,geometry,satellite,instrument,start,end,epoch,sat_alt,sat_az,sat_sunlit,solar_alt,solar_az,solar_time,access,revisit
0,1,POINT (0.00000 0.00000),test,lead instr,2021-01-01 19:43:09.096639+00:00,2021-01-01 19:47:46.049030+00:00,2021-01-01 19:45:27.727672+00:00,0.696197,70.429515,False,-23.279858,244.905640,19.694145,0 days 00:04:36.952391,NaT
1,1,POINT (0.00000 0.00000),test,lead instr,2021-01-01 23:20:34.563760+00:00,2021-01-01 23:39:06.059843+00:00,2021-01-01 23:29:46.215525+00:00,19.600343,253.168221,False,-65.629933,199.337905,23.431272,0 days 00:18:31.496083,0 days 03:55:56.963204
2,1,POINT (0.00000 0.00000),test,lead instr,2021-01-02 08:04:34.515457+00:00,2021-01-02 08:18:21.655247+00:00,2021-01-02 08:11:30.939792+00:00,7.780613,107.925135,True,29.098603,116.423839,8.124036,0 days 00:13:47.139790,0 days 08:57:47.091487
3,1,POINT (0.00000 0.00000),test,lead instr,2021-01-02 11:48:22.512950+00:00,2021-01-02 12:03:32.938751+00:00,2021-01-02 11:55:56.414009+00:00,10.041902,288.012514,True,67.044929,175.153994,11.863386,0 days 00:15:10.425801,0 days 03:58:58.423294
4,1,POINT (0.00000 0.00000),test,lead instr,2021-01-02 20:28:32.195931+00:00,2021-01-02 20:46:18.810745+00:00,2021-01-02 20:37:26.647830+00:00,16.636926,72.618019,False,-34.823911,241.790954,20.552491,0 days 00:17:46.614814,0 days 08:57:56.297795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,1,POINT (0.00000 0.00000),test,lead instr,2021-01-30 11:52:31.075151+00:00,2021-01-30 12:06:33.533426+00:00,2021-01-30 11:59:30.596995+00:00,8.306894,288.125958,True,72.154461,169.206635,11.769990,0 days 00:14:02.458275,0 days 03:58:44.697237
102,1,POINT (0.00000 0.00000),test,lead instr,2021-01-30 20:31:47.173549+00:00,2021-01-30 20:50:18.651850+00:00,2021-01-30 20:41:04.970966+00:00,18.836790,72.839044,False,-34.981490,248.571496,20.462114,0 days 00:18:31.478301,0 days 08:57:47.576699
103,1,POINT (0.00000 0.00000),test,lead instr,2021-01-31 00:22:00.898985+00:00,2021-01-31 00:28:49.933500+00:00,2021-01-31 00:25:24.752597+00:00,1.541798,250.910798,False,-72.375765,170.484822,0.200412,0 days 00:06:49.034515,0 days 03:57:02.759951
104,1,POINT (0.00000 0.00000),test,lead instr,2021-01-31 08:57:03.788377+00:00,2021-01-31 09:17:17.949564+00:00,2021-01-31 09:07:13.875754+00:00,31.220734,106.439906,True,41.045110,113.185714,8.896389,0 days 00:20:14.161187,0 days 08:55:17.050579
105,1,POINT (0.00000 0.00000),test,lead instr,2021-01-31 10:49:19.977911+00:00,2021-01-31 11:09:54.442106+00:00,2021-01-31 10:59:36.316229+00:00,34.690831,286.440563,True,64.939033,134.439299,10.769174,0 days 00:20:34.464195,0 days 02:12:50.653729